#include(${CTEST_SCRIPT_DIRECTORY}/project_name.cmake)
include(${CTEST_SCRIPT_DIRECTORY}/cmakegui_config.cmake)

if(NOT DEFINED CTEST_PROJECT_NAME)
	message(FATAL_ERROR "CTEST_PROJECT_NAME not defined!")
endif()

if(NOT DEFINED CTEST_SOURCE_DIRECTORY)
	message(FATAL_ERROR "CTEST_SOURCE_DIRECTORY not defined!")
endif()

if(NOT DEFINED CTEST_BINARY_DIRECTORY)
	message(FATAL_ERROR "CTEST_BINARY_DIRECTORY not defined!")
endif()

#Clean previous pipeline run
#ctest_empty_binary_directory(${CTEST_BINARY_DIRECTORY})


CTEST_START(Experimental)
set(CTEST_CONFIGURE_COMMAND "${CMAKE_COMMAND}")
set(CTEST_CONFIGURE_COMMAND "${CTEST_CONFIGURE_COMMAND} \"-G${CTEST_CMAKE_GENERATOR}\"")
set(CTEST_CONFIGURE_COMMAND "${CTEST_CONFIGURE_COMMAND} \"${CTEST_SOURCE_DIRECTORY}\"")
message("CTEST_CMAKE_GENERATOR:" ${CTEST_CMAKE_GENERATOR})
CTEST_CONFIGURE(BUILD "${CTEST_BINARY_DIRECTORY}" SOURCE "${CTEST_SOURCE_DIRECTORY}" RETURN_VALUE ret_val)
CTEST_CONFIGURE(BUILD "${CTEST_BINARY_DIRECTORY}" SOURCE "${CTEST_SOURCE_DIRECTORY}" RETURN_VALUE ret_val)