include(${CTEST_SCRIPT_DIRECTORY}/cmakegui_config.cmake)

if(NOT DEFINED CTEST_PROJECT_NAME)
	message(FATAL_ERROR "CTEST_PROJECT_NAME not defined!")
endif()

CTEST_START(Experimental)
CTEST_BUILD(BUILD "${CTEST_BINARY_DIRECTORY}" RETURN_VALUE res)
CTEST_BUILD(BUILD "${CTEST_BINARY_DIRECTORY}" RETURN_VALUE res)